# Generated by Django 2.0.3 on 2018-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0002_auto_20180403_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookstack',
            unique_together=set(),
        ),
    ]
