# Generated by Django 2.0.3 on 2018-04-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookstack", "0004_auto_20180408_1953"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookstack",
            options={"ordering": ("position",)},
        ),
        migrations.AlterUniqueTogether(
            name="bookstack",
            unique_together={("position", "stack")},
        ),
    ]
