# Generated by Django 3.2.2 on 2021-05-09 15:13

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("bookstack", "0005_auto_20180422_1429"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookstack",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="bookstack",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("position", "stack"),
                name="bookstack_position",
            ),
        ),
    ]
